### ISSUE TITLE
🖼️ Add website screenshot to readme.md (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/davfoundation.github.io#14]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### davfoundation.github.io

The DAV project you are looking at is `davfoundation.github.io`. It is the source of https://dav.network

### The Issue

The screenshot for the website is missing in the readme.
Add the following code to `README.md` below the badges.
```
<img src="./img/website_thumb.jpg" width="200" align="right" />
```

### Contributing to Community

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [davfoundation.github.io GitHub page](https://github.com/DAVFoundation/davfoundation.github.io) and click the ★ Star and then ⑂ Fork buttons
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/davfoundation.github.io.git`
- [ ] **Make changes in the README.md file**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/davfoundation.github.io](https://github.com/YOUR-USER-NAME/davfoundation.github.io)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#1`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by robatronPrime** [comment]
Hi, I would like to do this if that's fine with you.

**Comment by TalAter** [comment]
Looks great @robatronPrime 
Thank you so much for the help, and congrats on taking the first steps into the open source world!

Please join us on our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors) for more opportunities to contribute to open source and DAV.
