### ISSUE TITLE
Update copyright line from 2017 to 2018 (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/davfoundation.github.io#16]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### davfoundation.github.io

The DAV project you are looking at is `davfoundation.github.io`. It is the source of https://dav.network

### The Issue

From DAV, we wish you a happy new year, and as we enter the year 2018 we like to update our copyright notices to the current year. Change the year of copyright from `2017` to `2018` in the footer notes of all the .html files mentioned [here](https://github.com/DAVFoundation/davfoundation.github.io/search?l=HTML&q=2017&type=&utf8=%E2%9C%93)

### Contributing to Community

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [davfoundation.github.io GitHub page](https://github.com/DAVFoundation/davfoundation.github.io) and click the ★ Star and then ⑂ Fork buttons
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/davfoundation.github.io.git`
- [ ] **Make the necessary changes **
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/davfoundation.github.io](https://github.com/YOUR-USER-NAME/davfoundation.github.io)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#1`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by Justme764** [comment]
@cg-cnu   how do I get a key so i don't have to keep putting in my password.  I would like to practice the command line cloning, new branches, etc...  Thanks for any help.

**Comment by Justme764** [comment]
@cg-cnu  i'll take this one too.  I jhave completed.  

please note: I see I spelled copy write in the update messages instead of copyright.  the file are correct just not the update info. sorry it's late.  tomorrow is another day for learning,  Keep putting those issue's out there.  love it and learning a lot.  again thanks

**Comment by cg-cnu** [comment]
# This issue is still available for first-times to pickup

**Comment by michielvanhaverbeke** [comment]
I would like to take it on

**Comment by cg-cnu** [comment]
Sure @michielvanhaverbeke Go ahead 👍

**Comment by cg-cnu** [comment]
Congratulations @michielvanhaverbeke on your first contribution to opensource 👏 Thanks for taking the time to work on this one. Feel free to join our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors) to get updates from DAV and find out more opportunities to work on opensource.
