### ISSUE TITLE
🖼️ Add website screenshot to readme (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/davfoundation.github.io#22]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### davfoundation.github.io

The DAV project you are looking at is `davfoundation.github.io`. It is the source of https://dav.network

### The Issue

Readme.md used to have a screenshot showing the look and feel of the the website. Its broken right now. 

![screen shot 2018-02-14 at 10 11 34 pm](https://user-images.githubusercontent.com/2767425/36216323-77047170-11d4-11e8-830e-d594de24eb54.png)

Add a screenshot of the https://dav.network site to the `/img/` folder with the name `website_thumb.jpg` to make the image in readme.md live again. 

### Contributing to Community

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [davfoundation.github.io GitHub page](https://github.com/DAVFoundation/davfoundation.github.io) and click the ★ Star and then ⑂ Fork buttons
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/davfoundation.github.io.git`
- [ ] **Make changes in the README.md file**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/davfoundation.github.io](https://github.com/YOUR-USER-NAME/davfoundation.github.io)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#1`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by cg-cnu** [comment]
Go ahead @tashachin its yours!

**Comment by tashachin** [comment]
When I was following step 4
>> Clone a copy to your local machine with $ git clone git@github.com:YOUR-GITHUB-USER-NAME/davfoundation.github.io.git

I got an error (I'll attach a screenshot).
![screen shot 2018-02-15 at 11 47 31 am](https://user-images.githubusercontent.com/27714199/36278199-e5fd7a9a-1247-11e8-8268-e1a76366d4a3.png)


I was able to get around it by manually cloning my fork.

**Comment by cg-cnu** [comment]
@tashachin Thanks for pointing that out. Will fix it in our next issues! 👍

**Comment by cg-cnu** [comment]
Congratulations @tashachin on your first contribution to open source 🎆 👏 
The pr will be merged soon. I am closing this issue for now!
Feel free to join our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors/) to find out about more opportunities to contribute 🙂
