### ISSUE TITLE
telegram view group link broken

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/davfoundation.github.io#24]
## Expected Behavior

Clicking on the telegram icon in the header is redirecting me to http://t.me/DAVNetwork which has the DAV Network `view group` button. Clicking on the button is redirecting to `tg://resolve?domain=DAVNetwork` which should display the group. The `open in web` button is working fine. 

## Current Behavior

The `tg://resolve?domain=DAVNetwork` link is broken.

**Comment by TalAter** [comment]
That is how Telegram behaves. The first link is for people that have the Telegram app installed
